const peliculas = [
  {
    id: "superman",
    titulo: "Superman",
    poster: "img-pelis/Superman.jpg",
    genero: "Acción",
    duracionMinutos: 130,
    clasificacion: "+13",
    sinopsis: "El último hijo de Krypton vive entre dos mundos: reportero de día y símbolo de esperanza siempre. Cuando una amenaza pone en jaque a la humanidad, deberá demostrar que su mayor fuerza no son sus poderes, sino su corazón.",
    funciones: [
      { id: "superman-f1", hora: "14:00", sala: "Sala 1", precio: 5 },
      { id: "superman-f2", hora: "16:30", sala: "Sala 3", precio: 5 },
      { id: "superman-f3", hora: "19:00", sala: "Sala 1", precio: 5 },
      { id: "superman-f4", hora: "21:30", sala: "Sala 2", precio: 5 },
    ],
  },
  {
    id: "batman",
    titulo: "Batman",
    poster: "img-pelis/Batman.jpg",
    genero: "Acción",
    duracionMinutos: 120,
    clasificacion: "+16",
    sinopsis: "En una Gotham consumida por el crimen, un detective enmascarado persigue a un asesino que deja acertijos. La investigación lo obliga a enfrentar la corrupción de su propia ciudad.",
    funciones: [
      { id: "batman-f1", hora: "15:00", sala: "Sala 2", precio: 5 },
      { id: "batman-f2", hora: "18:00", sala: "Sala 4", precio: 5 },
      { id: "batman-f3", hora: "20:30", sala: "Sala 1", precio: 5 },
      { id: "batman-f4", hora: "22:45", sala: "Sala 3", precio: 5 },
    ],
  },
  {
    id: "shrek",
    titulo: "Shrek",
    poster: "img-pelis/Shrekban.jpg",
    genero: "Animación",
    duracionMinutos: 90,
    clasificacion: "ATP",
    sinopsis: "Un ogro gruñón ve su pantano invadido por criaturas de cuento. Para recuperar su soledad acepta rescatar a una princesa, sin imaginar que ese viaje le cambiará la vida.",
    funciones: [
      { id: "shrek-f1", hora: "13:30", sala: "Sala 5", precio: 5 },
      { id: "shrek-f2", hora: "15:45", sala: "Sala 2", precio: 5 },
      { id: "shrek-f3", hora: "17:30", sala: "Sala 1", precio: 5 },
    ],
  },
  {
    id: "blade-runner",
    titulo: "Blade Runner",
    poster: "img-pelis/Blade-runer.jpg",
    genero: "Ciencia Ficción",
    duracionMinutos: 117,
    clasificacion: "+16",
    sinopsis: "En un futuro lluvioso, un cazador de replicantes recibe una última misión. Entre humanos y máquinas, la línea que los separa empieza a desdibujarse.",
    funciones: [
      { id: "blade-runner-f1", hora: "16:00", sala: "Sala 3", precio: 5 },
      { id: "blade-runner-f2", hora: "19:15", sala: "Sala 4", precio: 5 },
      { id: "blade-runner-f3", hora: "22:00", sala: "Sala 2", precio: 5 },
    ],
  },
  {
    id: "shaolin-soccer",
    titulo: "Shaolin Soccer",
    poster: "img-pelis/Shaolin-Soccer.jpg",
    genero: "Comedia",
    duracionMinutos: 113,
    clasificacion: "+13",
    sinopsis: "Un maestro de kung-fu venido a menos descubre a un joven con una patada extraordinaria. Juntos arman un equipo que mezcla artes marciales y fútbol.",
    funciones: [
      { id: "shaolin-soccer-f1", hora: "14:30", sala: "Sala 1", precio: 5 },
      { id: "shaolin-soccer-f2", hora: "17:00", sala: "Sala 5", precio: 5 },
      { id: "shaolin-soccer-f3", hora: "19:30", sala: "Sala 3", precio: 5 },
    ],
  },
  {
    id: "rey-leon",
    titulo: "El Rey León",
    poster: "img-pelis/Rey-leon.jpg",
    genero: "Animación",
    duracionMinutos: 88,
    clasificacion: "ATP",
    sinopsis: "Un joven león destinado a reinar huye tras una tragedia. Lejos de casa aprende quién es realmente, hasta que el deber lo llama de vuelta.",
    funciones: [
      { id: "rey-leon-f1", hora: "13:00", sala: "Sala 2", precio: 5 },
      { id: "rey-leon-f2", hora: "15:30", sala: "Sala 1", precio: 5 },
      { id: "rey-leon-f3", hora: "18:15", sala: "Sala 4", precio: 5 },
    ],
  },
  {
    id: "gato-con-botas",
    titulo: "El Gato con Botas",
    poster: "img-pelis/Gato-con-Botas.jpg",
    genero: "Animación",
    duracionMinutos: 90,
    clasificacion: "ATP",
    sinopsis: "El felino más audaz y galán emprende una aventura para recuperar las nueve vidas que fue perdiendo. En el camino descubre lo que de verdad importa.",
    funciones: [
      { id: "gato-con-botas-f1", hora: "14:15", sala: "Sala 5", precio: 5 },
      { id: "gato-con-botas-f2", hora: "16:45", sala: "Sala 2", precio: 5 },
      { id: "gato-con-botas-f3", hora: "18:30", sala: "Sala 1", precio: 5 },
    ],
  },
  {
    id: "deadpool",
    titulo: "Deadpool",
    poster: "img-pelis/Deadpool.jpg",
    genero: "Acción",
    duracionMinutos: 108,
    clasificacion: "+18",
    sinopsis: "Un mercenario con humor ácido y un factor de curación imparable busca venganza. Romperá todas las reglas (y la cuarta pared) para conseguirla.",
    funciones: [
      { id: "deadpool-f1", hora: "17:45", sala: "Sala 3", precio: 5 },
      { id: "deadpool-f2", hora: "20:00", sala: "Sala 1", precio: 5 },
      { id: "deadpool-f3", hora: "22:30", sala: "Sala 4", precio: 5 },
    ],
  },
];
